spring.application.name=dispatch-engine
server.port=8082

spring.cloud.aws.region.static=ap-southeast-2
spring.cloud.aws.credentials.type=default

aws.sqs.dispatch-queue=https://sqs.ap-southeast-2.amazonaws.com/984454382434/dispatch-orders
aws.sns.dispatch-topic-arn=arn:aws:sns:ap-southeast-2:984454382434:dispatch-events
aws.dynamodb.table-name=dispatch-engine-assignments
aws.driver-api.url=https://driver-api.lastmile.internal

resilience4j.circuitbreaker.instances.driverApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.driverApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.driverApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.driverApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.driverApi.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.instances.driverApi.maxAttempts=3
resilience4j.retry.instances.driverApi.waitDuration=500ms
resilience4j.retry.instances.driverApi.enableExponentialBackoff=true
resilience4j.retry.instances.driverApi.exponentialBackoffMultiplier=2

resilience4j.bulkhead.instances.driverApi.maxConcurrentCalls=10
resilience4j.bulkhead.instances.driverApi.maxWaitDuration=100ms
